import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "thirdweb/react";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EduChain",
  description: "Generated by FutureITech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.variable}>
        <ThirdwebProvider>
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  );
}
